spring:
  application:
    name: todo
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: ${PORT:3001}

springdoc:
  swagger-ui:
    path: /api
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
